import Header from "@/components/header/Header";
import "../styles/globals.css";
import Campaigns from "@/components/ui/Campaigns";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
        <Campaigns />
      </body>
    </html>
  );
}
